export const mockDataCode = [
    {
      id: 1,
      nome: "Pizzeria Paolo",
      numPersone: 2, 
      tempoMedioPersona: 5,
      tipoCoda: "ordinaria",
      listaPersone: [1,2],
    },
    {
      id: 2,
      nome: "Farmacia 1",
      numPersone: 2, //listaPersone.length
      tempoMedioPersona: 5,
      tipoCoda: "ordinaria",
      listaPersone: [2,3],
    },
    {
      id: 3,
      nome: "Ristorante Giovanni",
      numPersone: 4, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: [2,3],
    },
    {
      id: 4,
      nome: "Panetteria",
      numPersone: 4, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: [2,3],
    },
    {
      id: 5,
      nome: "Dottore Andrea M.",
      numPersone: 6, 
      tempoMedioPersona: 20,
      tipoCoda: "ordinaria",
      listaPersone: [2,3],
    },
    {
      id: 6,
      nome: "Salumiere",
      numPersone: 4, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: [2,3],
    },
    {
      id: 7,
      nome: "Farmacia 2",
      numPersone: 4, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: [2,3],
    },
    {
      id: 8,
      nome: "Dottore Paolo R.",
      numPersone: 4, 
      tempoMedioPersona: 30,
      tipoCoda: "ordinaria",
      listaPersone: [2,3],
    },
    {
      id: 9,
      nome: "Macellaio",
      numPersone: 4, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: [2,3],
    },
    {
      id: 10,
      nome: "Ufficio A.",
      numPersone: 4, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: [2,3],
    },
  ];