import { mockDataUsersInLine } from "./mockDataUsersInLine";

export const mockDataCode = [
    {
      id: 1,
      nome: "Pizzeria Paolo",
      numPersone: mockDataUsersInLine.length, 
      tempoMedioPersona: 5,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
    {
      id: 2,
      nome: "Farmacia 1",
      numPersone: mockDataUsersInLine.length,
      tempoMedioPersona: 5,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
    {
      id: 3,
      nome: "Ristorante Giovanni",
      numPersone: mockDataUsersInLine.length, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
    {
      id: 4,
      nome: "Panetteria",
      numPersone: mockDataUsersInLine.length, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
    {
      id: 5,
      nome: "Dottore Andrea M.",
      numPersone: mockDataUsersInLine.length, 
      tempoMedioPersona: 20,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
    {
      id: 6,
      nome: "Salumiere",
      numPersone: mockDataUsersInLine.length, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
    {
      id: 7,
      nome: "Farmacia 2",
      numPersone: mockDataUsersInLine.length, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
    {
      id: 8,
      nome: "Dottore Paolo R.",
      numPersone: mockDataUsersInLine.length, 
      tempoMedioPersona: 30,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
    {
      id: 9,
      nome: "Macellaio",
      numPersone: mockDataUsersInLine.length, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
    {
      id: 10,
      nome: "Ufficio A.",
      numPersone: mockDataUsersInLine.length, 
      tempoMedioPersona: 4,
      tipoCoda: "ordinaria",
      listaPersone: mockDataUsersInLine.length,
    },
  ];